#!/bin/bash

PSQL="psql -X --username=postgres --dbname=bikes --tuples-only -c"
PSQL_CreateDatabase="psql -X --username=postgres --dbname=postgres --tuples-only -c"

gum style --border normal --margin "1" --padding "1 2 " --border-foreground 212 "Hello, there! Welcome to $(gum style --foreround 212 'Derek's Vultr Arch Linux PostgREST Setup)."

MAIN_MENU(){
	if [[ $1 ]]
	then
		echo -e "\n$1"
	fi
	echo -e "\n~~~~~ Bike Rental Shop ~~~~~"
	echo -e "\n0. Database Management Menu\n1. Rent a Bike\n2. Return a Bike\n3. Exit Program\n"
	echo "Enter Command: "
	read MAIN_MENU_SELECTION
	case $MAIN_MENU_SELECTION in
	0) DATABASE_MANAGEMENT_MENU ;;
	1) RENT_MENU ;;
	2) RETURN_MENU ;;
	3) EXIT ;;
	*) MAIN_MENU "Please enter a valid option." ;;
esac
}